spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  logging:
    pattern:
      dateformat: "yyyy-MM-dd HH:mm:ss"
  devtools:
    add-properties: false
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
logging:
  level:
    org:
      springframework:
        security: DEBUG
server:
  port: 8080