spring:
  datasource:
    url: ${JDBC_DATASOURCE_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    sql:
      init:
        mode: always

server:
  port: ${PORT:10000}
  address: 0.0.0.0

logging:
  level:
    ROOT: INFO
    org:
      springframework:
        security: INFO