spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  logging:
    pattern:
      dateformat: "yyyy-MM-dd HH:mm:ss"
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem