spring:
  datasource:
    username: ""
    password: ""
    url: "jdbc:h2:./taskManager"

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true

server:
  error:
    include-stacktrace: on_param

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    web: DEBUG