spring:
  datasource:
    url: ${JDBC_DATASOURCE_URL}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
  devtools:
    add-properties: false
  main:
    web-application-type: servlet

server:
  port: ${PORT:8080}
  address: 0.0.0.0

logging:
  level:
    org:
      springframework:
        security: INFO