spring:
  application:
    name: taskManager
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  logging:
    pattern:
      dateformat: "yyyy-MM-dd HH:mm:ss"
  mvc:
    hiddenmethod:
      filter:
        enabled: true

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: ${PORT:8080}

base-url: /api